// src/utils/grammarPatternInstaller.js
// Pure installer API — no React imports, no store imports.
// Returns config patches; caller decides how to apply them.

import { getPatternById, GRAMMAR_PATTERNS } from './grammarPatternLibrary.js';

// ── Helpers ────────────────────────────────────────────────────────────────

let _seq = 0;
function generateInstanceSuffix() {
    const ts = Date.now().toString(36);
    const rand = Math.random().toString(36).substring(2, 6);
    return `${ts}${rand}${_seq++ % 36}`;
}

// ── Public API ─────────────────────────────────────────────────────────────

/**
 * Look up a pattern definition by ID.
 * @param {string} patternId
 * @returns {object|null}
 */
export function getPattern(patternId) {
    return getPatternById(patternId);
}

/**
 * Get all available patterns, optionally filtered by category.
 * @param {string} [category]
 * @returns {object[]}
 */
export function getAllPatterns(category) {
    if (!category) return GRAMMAR_PATTERNS;
    return GRAMMAR_PATTERNS.filter(p => p.category === category);
}

/**
 * Return default options for a pattern.
 * @param {object} pattern
 * @returns {object}
 */
export function getDefaultOptions(pattern) {
    if (!pattern?.options) return {};
    const defaults = {};
    for (const opt of pattern.options) {
        if (opt.defaultValue !== undefined) {
            defaults[opt.id] = Array.isArray(opt.defaultValue)
                ? [...opt.defaultValue]
                : opt.defaultValue;
        }
    }
    return defaults;
}

/**
 * Generate an instance ID for a pattern installation.
 * @param {string} patternId
 * @returns {string}
 */
export function makeInstanceId(patternId) {
    return `gpl_${patternId.replace(/\./g, '_')}_${generateInstanceSuffix()}`;
}

/**
 * Preview what installing a pattern would produce without applying it.
 * @param {string} patternId
 * @param {object} options
 * @param {object} currentConfig  — full config object from useConfigStore
 * @returns {{ patch: object, report: object }}
 */
export function previewPatternInstall(patternId, options, currentConfig) {
    return _buildInstall(patternId, options, currentConfig, new Date());
}

/**
 * Build config patch for installing a pattern.
 * @param {string} patternId
 * @param {object} options
 * @param {object} currentConfig
 * @param {Date}   [now]
 * @returns {{ patch: object, report: object }}
 */
export function installPattern(patternId, options, currentConfig, now = new Date()) {
    return _buildInstall(patternId, options, currentConfig, now);
}

/**
 * Build config patch for uninstalling a pattern instance.
 * Removes only rules generated by this instance.
 * @param {string} instanceId
 * @param {object} currentConfig
 * @returns {{ patch: object, report: object }}
 */
export function uninstallPattern(instanceId, currentConfig) {
    const installed = currentConfig.installedGrammarPatterns || [];
    const meta = installed.find(m => m.instanceId === instanceId);
    if (!meta) {
        return { patch: {}, report: { error: `Instance ${instanceId} not found.` } };
    }

    const idsToRemove = new Set(meta.generatedRuleIds || []);

    // Filter out generated rules
    const nextRules = (currentConfig.grammarRules || []).filter(
        r => !idsToRemove.has(r.id)
    );

    // Filter out Word Assist triggers from this pattern
    const triggers = currentConfig.wordAssistConfig?.triggers || [];
    const nextTriggers = triggers.filter(
        t => t.sourcePatternInstanceId !== instanceId
    );

    const nextWaConfig = { ...currentConfig.wordAssistConfig, triggers: nextTriggers };

    // Remove metadata entry
    const nextInstalled = installed.filter(m => m.instanceId !== instanceId);

    const patch = {
        grammarRules: nextRules,
        installedGrammarPatterns: nextInstalled
    };

    // Only include wordAssistConfig if we actually removed triggers
    if (nextTriggers.length !== triggers.length) {
        patch.wordAssistConfig = nextWaConfig;
    }

    return {
        patch,
        report: {
            removedRuleCount: idsToRemove.size,
            removedTriggerCount: triggers.length - nextTriggers.length,
            patternName: meta.name
        }
    };
}

/**
 * Detect conflicts between generated rules and existing config.
 * @param {object} generatedPatch — output of pattern.build()
 * @param {object} currentConfig
 * @returns {{ conflicts: string[], warnings: string[] }}
 */
export function detectPatternConflicts(generatedPatch, currentConfig) {
    const conflicts = [];
    const warnings = [];

    const existingRules = currentConfig.grammarRules || [];
    const existingNames = new Set(existingRules.map(r => (r.name || '').toLowerCase()));
    const existingIds   = new Set(existingRules.map(r => r.id));

    const existingWATriggers = (currentConfig.wordAssistConfig?.triggers || []);
    const existingWAIds = new Set(existingWATriggers.map(t => t.id));

    for (const rule of (generatedPatch.grammarRules || [])) {
        if (existingIds.has(rule.id)) {
            conflicts.push(`Rule ID already exists: ${rule.id}`);
        }
        if (existingNames.has((rule.name || '').toLowerCase())) {
            warnings.push(`Rule name "${rule.name}" already exists — both will be kept.`);
        }
    }

    for (const trigger of (generatedPatch.wordAssistConfigPatch?.triggers || [])) {
        if (existingWAIds.has(trigger.id)) {
            conflicts.push(`Word Assist trigger ID already exists: ${trigger.id}`);
        }
    }

    return { conflicts, warnings };
}

// ── Internal ───────────────────────────────────────────────────────────────

function _buildInstall(patternId, options, currentConfig, now) {
    const pattern = getPatternById(patternId);
    if (!pattern) {
        return { patch: {}, report: { error: `Unknown pattern: ${patternId}` } };
    }

    const instanceId = makeInstanceId(patternId);
    const generated = pattern.build({ options: options || getDefaultOptions(pattern), currentConfig, instanceId });

    // Conflict detection
    const { conflicts, warnings } = detectPatternConflicts(generated, currentConfig);
    if (conflicts.length > 0) {
        return { patch: {}, report: { error: 'Conflicts detected', conflicts, warnings } };
    }

    // Build merged patch
    const existingRules = currentConfig.grammarRules || [];
    const newRules = generated.grammarRules || [];

    const existingTriggers = currentConfig.wordAssistConfig?.triggers || [];
    const newTriggers = (generated.wordAssistConfigPatch?.triggers || [])
        .map(t => ({ ...t, sourcePatternInstanceId: instanceId }));

    const nextWaConfig = newTriggers.length > 0
        ? { ...currentConfig.wordAssistConfig, triggers: [...existingTriggers, ...newTriggers] }
        : currentConfig.wordAssistConfig;

    // Collect custom word classes from pattern
    const existingClasses = currentConfig.customWordClasses || [];
    const newClasses = (generated.customWordClasses || []).filter(
        c => !existingClasses.includes(c)
    );

    // Metadata
    const meta = {
        instanceId,
        patternId,
        patternVersion: pattern.version,
        name: pattern.name,
        installedAt: now.toISOString(),
        generatedRuleIds: newRules.map(r => r.id),
        configKeysTouched: ['grammarRules'],
        options: options || getDefaultOptions(pattern)
    };

    if (newTriggers.length > 0) meta.configKeysTouched.push('wordAssistConfig');
    if (newClasses.length > 0)  meta.configKeysTouched.push('customWordClasses');

    const nextInstalled = [...(currentConfig.installedGrammarPatterns || []), meta];

    const patch = {
        grammarRules: [...existingRules, ...newRules],
        installedGrammarPatterns: nextInstalled
    };
    if (newTriggers.length > 0) patch.wordAssistConfig = nextWaConfig;
    if (newClasses.length > 0)  patch.customWordClasses = [...existingClasses, ...newClasses];

    return {
        patch,
        report: {
            addedRules: newRules.map(r => r.name),
            addedTriggers: newTriggers.length,
            skippedRules: [],
            conflicts: [],
            warnings,
            instanceId,
            patternName: pattern.name
        }
    };
}
